### ISSUE TITLE
[BE] SpringBoot 프로젝트 생성 및 DB 연결

### ISSUE THREAD

**Issue by rxdcxdrnine** [rxdcxdrnine/what-you-see-is-what-you-git#5]
# Description

IntelliJ IDE 에서 Spring Initializer 를 이용한 SpringBoot 프로젝트를 생성하고, MySQL DB 에 스키마 생성 후 Spring 과 연결합니다.

# Todo

- [x] IntelliJ IDE 에서 Spring Initializer 를 이용한 SpringBoot 프로젝트 생성
- [x] MySQL DB 스키마 생성
- [x] SpringBoot 와 MySQL 연결
